name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: prod

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-fe:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-fe:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            docker-compose stop todo_fe
            docker system prune -af
            docker-compose pull todo_fe
            docker-compose up -d todo_fe
